[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/.netlify/builders/my-image-transformer"
  status = 200

[[redirects]]
  from = "/archive"
  to = "/.netlify/builders/my-archive-builder"
  status = 200
